<?php

namespace Inra2013\urzBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class GestionFichierController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Inra2013\urzBundle\Controller\GestionFichierController();
        return $instance;
    }
}
