<?php

namespace Inra2013\urzBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AnalyseController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Inra2013\urzBundle\Controller\AnalyseController();
        return $instance;
    }
}
