# Twig Configuration
twig:
    globals:
      
#Page d'accueil de l'application de
      Accueil: 
        
        #Titre de l'application
        Titre: UNITÉ DE RECHERCHE ZOOTECHNIQUE LABORATOIRE D'ANALYSE
        #Les liens se trouvant dans la partie Accueil
        Lien : 
          #Premier lien dans l'accueil,item:Barcode
           PremierLien: http://genomique.genotoul.fr/intranet/index.php?id=138
           ItemPremier: Barcode 
           #Deuxieme lien dans l'accueil
           DeuxiemeLien: http://genomique.genotoul.fr/intranet/index.php?id=133
           ItemDeuxieme: Document barcode
          
 #Partie administrative    
      Administrateur:
          
              #Les liens se trouvant dans la partie Administrative
        Lien : 
          PremierLien:
          ItemPremier:
          DeuxiemeLien:
          ItemDeuxieme:
            
#Partie Utilisateur  
      User:
             #Les liens se trouvant dans la partie Utilisateur

       Lien:
           
           ItemPremier :

       DeuxiemeLien:
               ItemDeuxieme:

#Partie Chercheur

      Chercheur:
        
        Lien :
          
            PremierLien :
            ItemPremier : 
            DeuxiemeLien:
            ItemDeuxieme:
              
              
#Valide le protocole(Code erreur)

      Valide:
        
        class:
            
            1 : info
            2 : success
            3 : error
            
        info:
            
            1 : En cours 
            2 : Validé
            3 : Refusé