## YAML Template.
---
#Chemin pour la Page d'accueil

Inra2013urzBundle_Homepage:
    pattern : /Home
    defaults: { _controller : Inra2013urzBundle:Agent:Index }

# Chemin pour la redirection de l'Agent qui se connecte
 
Inra2013urzBundle_Redirectionagent:
    pattern:   /redirection/agent
    defaults: { _controller: Inra2013urzBundle:Agent:Redirectionagent }
    
# Chemin pour la création de l'Agent

Inra2013urzBundle_ShowAgent:
    pattern: /Admin/Show/{Default}
    defaults: { _controller: Inra2013urzBundle:Agent:ShowAgent }  
    
    
# Chemin pour la création de l'Agent

Inra2013urzBundle_CreateAgent:
    pattern: /Admin/Create
    defaults: { _controller: Inra2013urzBundle:Agent:CreateAgent }
    
# Chemin pour la mise à jour de l'Agent par son id

Inra2013Bundle_UpdateAgent:
    pattern: /Admin/Update/{id}
    defaults: { _controller: Inra2013urzBundle:Agent:UpdateAgent}
    
    
# Chemin pour supprime l'Agent par son id    

Inra2013Bundle_DeleteAgent:
    pattern: /Admin/Delete/{id}
    defaults: { _controller: Inra2013urzBundle:Agent:DeleteAgent}
    
# Chemin pour active ou desactive l'Agent par son id 

Inra2013Bundle_ActiveAgent:
    pattern: /Admin/Active/{username}/{enable}
    defaults: { _controller: Inra2013urzBundle:Agent:ActivateAgent}  


    # Chemin pour l'upload du fichier excel et de la verification de son format et ...
    
Inra2013Bundle_UploadFile:
    pattern: /User/UploadFile
    defaults: { _controller: Inra2013urzBundle:GestionFichier:Upload }
    
    #Chemin pour la sauvegarde du fichier excel dans la base de données
    
Inra2013Bundle_SaveFile:
   pattern : /User/SaveFile
   defaults: { _controller : Inra2013urzBundle:GestionFichier:SaveExcel }
   
   # Chemin pour la création du fichier excel 
   
Inra2103Bundle_CreateExcel:
  pattern: /User/CreateExcel
  defaults: { _controller : Inra2013urzBundle:GestionFichier:CreateExcel }
  
  
  #Chemin pour la recherche du protocole dans un input
  
Inra2013Bundle_SearchProtocole:
   pattern: /Search/Protocole
   defaults: { _controller : Inra2013urzBundle:Analyse:SearchProtocole }
 