## YAML Template.
---
#Chemin pour la Page d'accueil

Inra2013urzBundle_Homepage:
    pattern : /Home
    defaults: { _controller : Inra2013urzBundle:Agent:Accueil }

# Chemin pour la redirection de l'Agent qui se connecte
 
Inra2013urzBundle_Redirectionagent:
    pattern:   /redirection/agent
    defaults: { _controller: Inra2013urzBundle:Agent:Redirectionagent }
    
# Chemin pour la création de l'Agent

Inra2013urzBundle_ShowAgent:
    pattern: /Admin/Show/{Default}
    defaults: { _controller: Inra2013urzBundle:Agent:ShowAgent }  
    
    
# Chemin pour la création de l'Agent

Inra2013urzBundle_CreateAgent:
    pattern: /Admin/Create
    defaults: { _controller: Inra2013urzBundle:Agent:CreateAgent }
    
# Chemin pour la mise à jour de l'Agent par son id

Inra2013Bundle_UpdateAgent:
    pattern: /Admin/Update/{id}
    defaults: { _controller: Inra2013urzBundle:Agent:UpdateAgent}
    
    
# Chemin pour supprime l'Agent par son id    

Inra2013Bundle_DeleteAgent:
    pattern: /Admin/Delete/{id}
    defaults: { _controller: Inra2013urzBundle:Agent:DeleteAgent}
    
# Chemin pour active ou desactive l'Agent par son id 

Inra2013Bundle_ActiveAgent:
    pattern: /Admin/Active/{username}/{enable}
    defaults: { _controller: Inra2013urzBundle:Agent:ActivateAgent}  


    # Chemin pour l'upload du fichier excel et de la verification de son format et ...
    
Inra2013Bundle_UploadFile:
    pattern: /User/UploadFile
    defaults: { _controller: Inra2013urzBundle:GestionFichier:Upload }
    
    #Chemin pour la sauvegarde du fichier excel dans la base de données
    
Inra2013Bundle_SaveFile:
   pattern : /User/SaveFile
   defaults: { _controller : Inra2013urzBundle:GestionFichier:SaveExcel }
   
   # Chemin pour la création du fichier excel 
   
Inra2013Bundle_CreateExcel:
  pattern: /User/CreateExcel
  defaults: { _controller : Inra2013urzBundle:GestionFichier:CreateExcel }
  
  #Chemin pour l'importation du listing des codelabo
   
Inra2013Bundle_ImportListing:
   pattern: /User/ImportListing
   defaults: { _controller : Inra2013urzBundle:GestionFichier:ImportListing }
   
   
  #Chemin pour l'importation des resultats dans un fichier excel
  
Inra2013Bundle_ImportResultat:
   pattern: /User/ImportResultat
   defaults: { _controller : Inra2013urzBundle:GestionFichier:ImportResultat } 

  #Chemin pour la recherche du protocole dans un input(requete json et ajax)
  
Inra2013Bundle_SearchProtocole:
   pattern: /Search/Protocole
   defaults: { _controller : Inra2013urzBundle:Analyse:SearchProtocole }
 
    #Chemin Pour la creation et update des analyses
 
Inra2013Bundle_CudAnalyse:
   pattern: /User/CudAnalyse
   defaults: { _controller : Inra2013urzBundle:Analyse:CudAnalyse }
 
 
    #Chemin pour voir partie des analyses avec role utlisateur laborantin
 
Inra2013Bundle_VoirAnalyse:
   pattern: /User/VoirAnalyse
   defaults: { _controller : Inra2013urzBundle:Analyse:VoirAnalyse }
  
  #Chemin pour voir partie des analyses avec role utlisateur laborantin
 
Inra2013Bundle_VoirAnalyseChercheur:
   pattern: /User/VoirAnalyseFini
   defaults: { _controller : Inra2013urzBundle:Analyse:VoirAnalyseChercheur }  
 #Chemin Pour la creation des analyses
 
Inra2013Bundle_CreateAnalyse:
   pattern: /User/CreateAnalyse
   defaults: { _controller : Inra2013urzBundle:Analyse:CreateAnalyse }
 
  #Chemin Pour la creation des analyses
 
Inra2013Bundle_UpdateAnalyse:
   pattern: /User/UpdateAnalyse
   defaults: { _controller : Inra2013urzBundle:Analyse:UpdateAnalyse }
   
 #Chemin pour voir les analyse d'un protocole qui est encours de validation
 
Inra2013urzBunle_VoirAnalyse:
  pattern: /User/VoirAnalyse/{numProtocole}
  defaults: { _controller : Inra2013urzBundle:Analyse:VoirAnalyse }
 
 #Chemin pour la creation d'un protocole
 
Inra2013Bundle_CreateProtocole:
   pattern: /CreateProtocole
   defaults: { _controller : Inra2013urzBundle:Analyse:CreateProtocole }
   
 #Chemin pour la recherche de la categorie des analyses(requete json et ajax)
   
Inra2013Bundle_SearchCategorieAnalyse:
   pattern: /Search/CategorieAnalyse
   defaults: { _controller : Inra2013urzBundle:Analyse:SearchAnalyseCategorie }
   
   
 #Chemin pour la recherche des types d analyse a partir de la categorie(requete json et ajax)
   
Inra2013Bundle_SearchTypeAnalyse :
   pattern: /Search/TypeAnalyse
   defaults: { _controller : Inra2013urzBundle:Analyse:SearchTypeAnalyse }
   
   #Chemin pour la recherche des champs d'une analyse pour mettre une formulé(requete json et ajax)
   
Inra2013Bundle_SearchChamp :
   pattern: /Search/Champ
   defaults: { _controller : Inra2013urzBundle:Analyse:SearchChamp }   
   
 #Chemin pour la validation du protocole par le laborantnin(e) 
 
Inra2013Bundle_ValidAnalyse :
   pattern: /User/Validation
   defaults: { _controller : Inra2013urzBundle:Analyse:ValidAnalyse }
   
   
   #Chemin pour la création d'une analyse dans une base de données
 
Inra2013Bundle_CreateAnalyseBdd :
   pattern: /User/AnalyseCreate
   defaults: { _controller : Inra2013urzBundle:Analyse:CreateAnalyseBdd }
   
   
#Chemin pour l'insertion de la formule dans la base de données pour un champs
 
Inra2013Bundle_FormuleChamp :
   pattern: /User/FormuleChamp
   defaults: { _controller : Inra2013urzBundle:Analyse:FormuleChamp }   
   
 #Chemin pour l'insertion de la formule dans la base de données pour un champs
 
Inra2013Bundle_Save :
   pattern: /User/Save/{Status}
   defaults: { _controller : Inra2013urzBundle:Analyse:Save }     